### ISSUE TITLE
unable to run fan-control in crontab

### ISSUE THREAD

**Issue by Tious13** [bastilmr/opi5-fan-control#1]
Hi, I have followed the instructions provided to install and run fan-control on an orangepi5. I'm very new in this domain and struggle to get crontab to run the program on startup/reboot.

To troubleshoot I then tried to run the program directly using
```./fan-control```
in the directory it was installed: /wiringOP/opi5-fan-control

I then get the following error: 

```
orangepi@orangepi5:~/wiringOP/opi5-fan-control$ ./fan-control
wiringPiSetup: Unable to open /dev/mem or /dev/gpiomem: No such file or directory.
  Aborting your program because if it can not access the GPIO
  hardware then it most certianly won't work
  Try running with sudo?
```

Running the same command with sudo worked after giving the device password.

lastly here is my crontab command if ever I made a mistake on it:

`@reboot /wiringOP/opi5-fan-control/fan-control`
 

What I understand so far is that I need to run crontab with the "sudo" permission. But there is no mention of this in your instructions. Have I overlocked a crucial step ? How can I set things up so ./fan-control doesn't need "permissions" ?

Thank you !

**Comment by GooeyTuxedo** [comment]
When you do the `crontab -e` step, run it as `sudo crontab -e` to edit the crontab for the root user.

**Comment by Tious13** [comment]
Thanks for your help !
just tested this method and it yields the same result upon reboot. Fan is set to 100% speed.

```
orangepi@orangepi5:~$ sudo crontab -e
[sudo] password for orangepi:
  GNU nano 5.4               /tmp/crontab.tUCN1p/crontab
@reboot /wiringOP/opi5-fan-control/fan-control

```

However. If this is the way to approach this, I'll redo an install of fan control in another folder and try again fresh.

I'll update the result here.

Cheers

**Comment by Tious13** [comment]
From a fresh install, got opi fan control in it's own folder
Executing it from there is working as it should. I then checked what is the proper path to access it and realised there were a few other levels above what I belived was the root folder


```
orangepi@orangepi5:~/opi5-fan-control$ sudo ./fan-control
[sudo] password for orangepi:
CPU: 26°C | PWM: 0%
CPU: 25°C | PWM: 0%
CPU: 25°C | PWM: 0%
CPU: 25°C | PWM: 0%
^C
orangepi@orangepi5:~/opi5-fan-control$ cd ..
orangepi@orangepi5:~$ ls
Desktop    Downloads  opi5-fan-control  Public     Videos
Documents  Music      Pictures          Templates  wiringOP
orangepi@orangepi5:~$ cd ..
orangepi@orangepi5:/home$ cd ..
orangepi@orangepi5:/$ ls
bin   dev  home  lost+found  mnt  proc  run   selinux  sys  usr
boot  etc  lib   media       opt  root  sbin  srv      tmp  var
orangepi@orangepi5:/$ cd ..
orangepi@orangepi5:/$ ls
bin   dev  home  lost+found  mnt  proc  run   selinux  sys  usr
boot  etc  lib   media       opt  root  sbin  srv      tmp  var
```

I'm inclined to conclude that my crontab command isn't properly written as I didn't really understand what was the root of the device (very new to all this).

In my case, I think the path to write down in crontab should be:
`/home/orangepi/opi-fan-control/fan-control`
and not 
`/opi-fan-control/fan-control`


I've replaced the sudo crontab command and things seems to work as they should now. 

Thanks for your help !
